/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.ManageAudience.Model;
using Linebotsdkx.ManageAudience.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.ManageAudience.Test.Model
{
    /// <summary>
    ///  Class for testing AudienceGroupType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AudienceGroupTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AudienceGroupType
        //private AudienceGroupType instance;

        public AudienceGroupTypeTests()
        {
            // TODO uncomment below to create an instance of AudienceGroupType
            //instance = new AudienceGroupType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AudienceGroupType
        /// </summary>
        [Fact]
        public void AudienceGroupTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" AudienceGroupType
            //Assert.IsType<AudienceGroupType>(instance);
        }
    }
}
