/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.ManageAudience.Model;
using Linebotsdkx.ManageAudience.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.ManageAudience.Test.Model
{
    /// <summary>
    ///  Class for testing AudienceGroupCreateRoute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AudienceGroupCreateRouteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AudienceGroupCreateRoute
        //private AudienceGroupCreateRoute instance;

        public AudienceGroupCreateRouteTests()
        {
            // TODO uncomment below to create an instance of AudienceGroupCreateRoute
            //instance = new AudienceGroupCreateRoute();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AudienceGroupCreateRoute
        /// </summary>
        [Fact]
        public void AudienceGroupCreateRouteInstanceTest()
        {
            // TODO uncomment below to test "IsType" AudienceGroupCreateRoute
            //Assert.IsType<AudienceGroupCreateRoute>(instance);
        }
    }
}
