/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.ManageAudience.Model;
using Linebotsdkx.ManageAudience.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.ManageAudience.Test.Model
{
    /// <summary>
    ///  Class for testing CreateClickBasedAudienceGroupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateClickBasedAudienceGroupResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateClickBasedAudienceGroupResponse
        //private CreateClickBasedAudienceGroupResponse instance;

        public CreateClickBasedAudienceGroupResponseTests()
        {
            // TODO uncomment below to create an instance of CreateClickBasedAudienceGroupResponse
            //instance = new CreateClickBasedAudienceGroupResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateClickBasedAudienceGroupResponse
        /// </summary>
        [Fact]
        public void CreateClickBasedAudienceGroupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateClickBasedAudienceGroupResponse
            //Assert.IsType<CreateClickBasedAudienceGroupResponse>(instance);
        }

        /// <summary>
        /// Test the property 'AudienceGroupId'
        /// </summary>
        [Fact]
        public void AudienceGroupIdTest()
        {
            // TODO unit test for the property 'AudienceGroupId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

        /// <summary>
        /// Test the property 'ClickUrl'
        /// </summary>
        [Fact]
        public void ClickUrlTest()
        {
            // TODO unit test for the property 'ClickUrl'
        }

        /// <summary>
        /// Test the property 'CreateRoute'
        /// </summary>
        [Fact]
        public void CreateRouteTest()
        {
            // TODO unit test for the property 'CreateRoute'
        }

        /// <summary>
        /// Test the property 'Permission'
        /// </summary>
        [Fact]
        public void PermissionTest()
        {
            // TODO unit test for the property 'Permission'
        }

        /// <summary>
        /// Test the property 'ExpireTimestamp'
        /// </summary>
        [Fact]
        public void ExpireTimestampTest()
        {
            // TODO unit test for the property 'ExpireTimestamp'
        }

        /// <summary>
        /// Test the property 'IsIfaAudience'
        /// </summary>
        [Fact]
        public void IsIfaAudienceTest()
        {
            // TODO unit test for the property 'IsIfaAudience'
        }
    }
}
