/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.ManageAudience.Model;
using Linebotsdkx.ManageAudience.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.ManageAudience.Test.Model
{
    /// <summary>
    ///  Class for testing CreateImpBasedAudienceGroupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateImpBasedAudienceGroupRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateImpBasedAudienceGroupRequest
        //private CreateImpBasedAudienceGroupRequest instance;

        public CreateImpBasedAudienceGroupRequestTests()
        {
            // TODO uncomment below to create an instance of CreateImpBasedAudienceGroupRequest
            //instance = new CreateImpBasedAudienceGroupRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateImpBasedAudienceGroupRequest
        /// </summary>
        [Fact]
        public void CreateImpBasedAudienceGroupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateImpBasedAudienceGroupRequest
            //Assert.IsType<CreateImpBasedAudienceGroupRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
    }
}
