/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.ManageAudience.Model;
using Linebotsdkx.ManageAudience.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.ManageAudience.Test.Model
{
    /// <summary>
    ///  Class for testing GetAudienceGroupsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAudienceGroupsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAudienceGroupsResponse
        //private GetAudienceGroupsResponse instance;

        public GetAudienceGroupsResponseTests()
        {
            // TODO uncomment below to create an instance of GetAudienceGroupsResponse
            //instance = new GetAudienceGroupsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAudienceGroupsResponse
        /// </summary>
        [Fact]
        public void GetAudienceGroupsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAudienceGroupsResponse
            //Assert.IsType<GetAudienceGroupsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'AudienceGroups'
        /// </summary>
        [Fact]
        public void AudienceGroupsTest()
        {
            // TODO unit test for the property 'AudienceGroups'
        }

        /// <summary>
        /// Test the property 'HasNextPage'
        /// </summary>
        [Fact]
        public void HasNextPageTest()
        {
            // TODO unit test for the property 'HasNextPage'
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'ReadWriteAudienceGroupTotalCount'
        /// </summary>
        [Fact]
        public void ReadWriteAudienceGroupTotalCountTest()
        {
            // TODO unit test for the property 'ReadWriteAudienceGroupTotalCount'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
    }
}
