/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.ManageAudience.Model;
using Linebotsdkx.ManageAudience.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.ManageAudience.Test.Model
{
    /// <summary>
    ///  Class for testing GetAudienceDataResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAudienceDataResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAudienceDataResponse
        //private GetAudienceDataResponse instance;

        public GetAudienceDataResponseTests()
        {
            // TODO uncomment below to create an instance of GetAudienceDataResponse
            //instance = new GetAudienceDataResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAudienceDataResponse
        /// </summary>
        [Fact]
        public void GetAudienceDataResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAudienceDataResponse
            //Assert.IsType<GetAudienceDataResponse>(instance);
        }

        /// <summary>
        /// Test the property 'AudienceGroup'
        /// </summary>
        [Fact]
        public void AudienceGroupTest()
        {
            // TODO unit test for the property 'AudienceGroup'
        }

        /// <summary>
        /// Test the property 'Jobs'
        /// </summary>
        [Fact]
        public void JobsTest()
        {
            // TODO unit test for the property 'Jobs'
        }
    }
}
