/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.ManageAudience.Model;
using Linebotsdkx.ManageAudience.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.ManageAudience.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateAudienceGroupAuthorityLevelRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateAudienceGroupAuthorityLevelRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateAudienceGroupAuthorityLevelRequest
        //private UpdateAudienceGroupAuthorityLevelRequest instance;

        public UpdateAudienceGroupAuthorityLevelRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateAudienceGroupAuthorityLevelRequest
            //instance = new UpdateAudienceGroupAuthorityLevelRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateAudienceGroupAuthorityLevelRequest
        /// </summary>
        [Fact]
        public void UpdateAudienceGroupAuthorityLevelRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateAudienceGroupAuthorityLevelRequest
            //Assert.IsType<UpdateAudienceGroupAuthorityLevelRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AuthorityLevel'
        /// </summary>
        [Fact]
        public void AuthorityLevelTest()
        {
            // TODO unit test for the property 'AuthorityLevel'
        }
    }
}
