/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Linebotsdkx.ManageAudience.Client.OpenAPIDateConverter;

namespace Linebotsdkx.ManageAudience.Model
{
    /// <summary>
    /// Failed type
    /// </summary>
    /// <value>Failed type</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AudienceGroupJobFailedType
    {
        /// <summary>
        /// Enum INTERNALERROR for value: INTERNAL_ERROR
        /// </summary>
        [EnumMember(Value = "INTERNAL_ERROR")]
        INTERNALERROR = 1,

        /// <summary>
        /// Enum AUDIENCEGROUPAUDIENCEINSUFFICIENT for value: AUDIENCE_GROUP_AUDIENCE_INSUFFICIENT
        /// </summary>
        [EnumMember(Value = "AUDIENCE_GROUP_AUDIENCE_INSUFFICIENT")]
        AUDIENCEGROUPAUDIENCEINSUFFICIENT = 2
    }

}
