/*
 * LINE Messaging API(Insight)
 *
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.Insight.Model;
using Linebotsdkx.Insight.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.Insight.Test.Model
{
    /// <summary>
    ///  Class for testing AppTypeTile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppTypeTileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppTypeTile
        //private AppTypeTile instance;

        public AppTypeTileTests()
        {
            // TODO uncomment below to create an instance of AppTypeTile
            //instance = new AppTypeTile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppTypeTile
        /// </summary>
        [Fact]
        public void AppTypeTileInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppTypeTile
            //Assert.IsType<AppTypeTile>(instance);
        }

        /// <summary>
        /// Test the property 'AppType'
        /// </summary>
        [Fact]
        public void AppTypeTest()
        {
            // TODO unit test for the property 'AppType'
        }

        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Fact]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }
    }
}
