/*
 * LINE Messaging API(Insight)
 *
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.Insight.Model;
using Linebotsdkx.Insight.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.Insight.Test.Model
{
    /// <summary>
    ///  Class for testing GetMessageEventResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMessageEventResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMessageEventResponse
        //private GetMessageEventResponse instance;

        public GetMessageEventResponseTests()
        {
            // TODO uncomment below to create an instance of GetMessageEventResponse
            //instance = new GetMessageEventResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMessageEventResponse
        /// </summary>
        [Fact]
        public void GetMessageEventResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMessageEventResponse
            //Assert.IsType<GetMessageEventResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Overview'
        /// </summary>
        [Fact]
        public void OverviewTest()
        {
            // TODO unit test for the property 'Overview'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

        /// <summary>
        /// Test the property 'Clicks'
        /// </summary>
        [Fact]
        public void ClicksTest()
        {
            // TODO unit test for the property 'Clicks'
        }
    }
}
