/*
 * LINE Messaging API(Insight)
 *
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.Insight.Model;
using Linebotsdkx.Insight.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.Insight.Test.Model
{
    /// <summary>
    ///  Class for testing GetMessageEventResponseClick
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMessageEventResponseClickTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMessageEventResponseClick
        //private GetMessageEventResponseClick instance;

        public GetMessageEventResponseClickTests()
        {
            // TODO uncomment below to create an instance of GetMessageEventResponseClick
            //instance = new GetMessageEventResponseClick();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMessageEventResponseClick
        /// </summary>
        [Fact]
        public void GetMessageEventResponseClickInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMessageEventResponseClick
            //Assert.IsType<GetMessageEventResponseClick>(instance);
        }

        /// <summary>
        /// Test the property 'Seq'
        /// </summary>
        [Fact]
        public void SeqTest()
        {
            // TODO unit test for the property 'Seq'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Click'
        /// </summary>
        [Fact]
        public void ClickTest()
        {
            // TODO unit test for the property 'Click'
        }

        /// <summary>
        /// Test the property 'UniqueClick'
        /// </summary>
        [Fact]
        public void UniqueClickTest()
        {
            // TODO unit test for the property 'UniqueClick'
        }

        /// <summary>
        /// Test the property 'UniqueClickOfRequest'
        /// </summary>
        [Fact]
        public void UniqueClickOfRequestTest()
        {
            // TODO unit test for the property 'UniqueClickOfRequest'
        }
    }
}
