/*
 * LINE Messaging API(Insight)
 *
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.Insight.Model;
using Linebotsdkx.Insight.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.Insight.Test.Model
{
    /// <summary>
    ///  Class for testing SubscriptionPeriodTile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubscriptionPeriodTileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubscriptionPeriodTile
        //private SubscriptionPeriodTile instance;

        public SubscriptionPeriodTileTests()
        {
            // TODO uncomment below to create an instance of SubscriptionPeriodTile
            //instance = new SubscriptionPeriodTile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubscriptionPeriodTile
        /// </summary>
        [Fact]
        public void SubscriptionPeriodTileInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubscriptionPeriodTile
            //Assert.IsType<SubscriptionPeriodTile>(instance);
        }

        /// <summary>
        /// Test the property 'SubscriptionPeriod'
        /// </summary>
        [Fact]
        public void SubscriptionPeriodTest()
        {
            // TODO unit test for the property 'SubscriptionPeriod'
        }

        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Fact]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }
    }
}
