/*
 * LIFF server API
 *
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.Liff.Model;
using Linebotsdkx.Liff.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.Liff.Test.Model
{
    /// <summary>
    ///  Class for testing AddLiffAppRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddLiffAppRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddLiffAppRequest
        //private AddLiffAppRequest instance;

        public AddLiffAppRequestTests()
        {
            // TODO uncomment below to create an instance of AddLiffAppRequest
            //instance = new AddLiffAppRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddLiffAppRequest
        /// </summary>
        [Fact]
        public void AddLiffAppRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddLiffAppRequest
            //Assert.IsType<AddLiffAppRequest>(instance);
        }

        /// <summary>
        /// Test the property 'View'
        /// </summary>
        [Fact]
        public void ViewTest()
        {
            // TODO unit test for the property 'View'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }

        /// <summary>
        /// Test the property 'PermanentLinkPattern'
        /// </summary>
        [Fact]
        public void PermanentLinkPatternTest()
        {
            // TODO unit test for the property 'PermanentLinkPattern'
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }

        /// <summary>
        /// Test the property 'BotPrompt'
        /// </summary>
        [Fact]
        public void BotPromptTest()
        {
            // TODO unit test for the property 'BotPrompt'
        }
    }
}
