/*
 * LIFF server API
 *
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.Liff.Model;
using Linebotsdkx.Liff.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.Liff.Test.Model
{
    /// <summary>
    ///  Class for testing GetAllLiffAppsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAllLiffAppsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAllLiffAppsResponse
        //private GetAllLiffAppsResponse instance;

        public GetAllLiffAppsResponseTests()
        {
            // TODO uncomment below to create an instance of GetAllLiffAppsResponse
            //instance = new GetAllLiffAppsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAllLiffAppsResponse
        /// </summary>
        [Fact]
        public void GetAllLiffAppsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAllLiffAppsResponse
            //Assert.IsType<GetAllLiffAppsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Apps'
        /// </summary>
        [Fact]
        public void AppsTest()
        {
            // TODO unit test for the property 'Apps'
        }
    }
}
