/*
 * LIFF server API
 *
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.Liff.Model;
using Linebotsdkx.Liff.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.Liff.Test.Model
{
    /// <summary>
    ///  Class for testing LiffView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LiffViewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LiffView
        //private LiffView instance;

        public LiffViewTests()
        {
            // TODO uncomment below to create an instance of LiffView
            //instance = new LiffView();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LiffView
        /// </summary>
        [Fact]
        public void LiffViewInstanceTest()
        {
            // TODO uncomment below to test "IsType" LiffView
            //Assert.IsType<LiffView>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'ModuleMode'
        /// </summary>
        [Fact]
        public void ModuleModeTest()
        {
            // TODO unit test for the property 'ModuleMode'
        }
    }
}
