/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Linebotsdkx.Webhook.Client;
using Linebotsdkx.Webhook.Model;

namespace Linebotsdkx.Webhook.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDummyApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// This is the dummy endpoint to generate the model classes
        /// </remarks>
        /// <exception cref="Linebotsdkx.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="callbackRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>string</returns>
        string Callback(CallbackRequest callbackRequest, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// This is the dummy endpoint to generate the model classes
        /// </remarks>
        /// <exception cref="Linebotsdkx.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="callbackRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> CallbackWithHttpInfo(CallbackRequest callbackRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDummyApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// This is the dummy endpoint to generate the model classes
        /// </remarks>
        /// <exception cref="Linebotsdkx.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="callbackRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> CallbackAsync(CallbackRequest callbackRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// This is the dummy endpoint to generate the model classes
        /// </remarks>
        /// <exception cref="Linebotsdkx.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="callbackRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> CallbackWithHttpInfoAsync(CallbackRequest callbackRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDummyApi : IDummyApiSync, IDummyApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DummyApi : IDummyApi
    {
        private Linebotsdkx.Webhook.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DummyApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DummyApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DummyApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DummyApi(string basePath)
        {
            this.Configuration = Linebotsdkx.Webhook.Client.Configuration.MergeConfigurations(
                Linebotsdkx.Webhook.Client.GlobalConfiguration.Instance,
                new Linebotsdkx.Webhook.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Linebotsdkx.Webhook.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Linebotsdkx.Webhook.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Linebotsdkx.Webhook.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DummyApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DummyApi(Linebotsdkx.Webhook.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Linebotsdkx.Webhook.Client.Configuration.MergeConfigurations(
                Linebotsdkx.Webhook.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Linebotsdkx.Webhook.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Linebotsdkx.Webhook.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Linebotsdkx.Webhook.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DummyApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DummyApi(Linebotsdkx.Webhook.Client.ISynchronousClient client, Linebotsdkx.Webhook.Client.IAsynchronousClient asyncClient, Linebotsdkx.Webhook.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Linebotsdkx.Webhook.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Linebotsdkx.Webhook.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Linebotsdkx.Webhook.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Linebotsdkx.Webhook.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Linebotsdkx.Webhook.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  This is the dummy endpoint to generate the model classes
        /// </summary>
        /// <exception cref="Linebotsdkx.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="callbackRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>string</returns>
        public string Callback(CallbackRequest callbackRequest, int operationIndex = 0)
        {
            Linebotsdkx.Webhook.Client.ApiResponse<string> localVarResponse = CallbackWithHttpInfo(callbackRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  This is the dummy endpoint to generate the model classes
        /// </summary>
        /// <exception cref="Linebotsdkx.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="callbackRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of string</returns>
        public Linebotsdkx.Webhook.Client.ApiResponse<string> CallbackWithHttpInfo(CallbackRequest callbackRequest, int operationIndex = 0)
        {
            // verify the required parameter 'callbackRequest' is set
            if (callbackRequest == null)
            {
                throw new Linebotsdkx.Webhook.Client.ApiException(400, "Missing required parameter 'callbackRequest' when calling DummyApi->Callback");
            }

            Linebotsdkx.Webhook.Client.RequestOptions localVarRequestOptions = new Linebotsdkx.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Linebotsdkx.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Linebotsdkx.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = callbackRequest;

            localVarRequestOptions.Operation = "DummyApi.Callback";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<string>("/callback", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Callback", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  This is the dummy endpoint to generate the model classes
        /// </summary>
        /// <exception cref="Linebotsdkx.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="callbackRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> CallbackAsync(CallbackRequest callbackRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Linebotsdkx.Webhook.Client.ApiResponse<string> localVarResponse = await CallbackWithHttpInfoAsync(callbackRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  This is the dummy endpoint to generate the model classes
        /// </summary>
        /// <exception cref="Linebotsdkx.Webhook.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="callbackRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<Linebotsdkx.Webhook.Client.ApiResponse<string>> CallbackWithHttpInfoAsync(CallbackRequest callbackRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'callbackRequest' is set
            if (callbackRequest == null)
            {
                throw new Linebotsdkx.Webhook.Client.ApiException(400, "Missing required parameter 'callbackRequest' when calling DummyApi->Callback");
            }


            Linebotsdkx.Webhook.Client.RequestOptions localVarRequestOptions = new Linebotsdkx.Webhook.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Linebotsdkx.Webhook.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Linebotsdkx.Webhook.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = callbackRequest;

            localVarRequestOptions.Operation = "DummyApi.Callback";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<string>("/callback", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Callback", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
