/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Linebotsdkx.Webhook.Client.OpenAPIDateConverter;

namespace Linebotsdkx.Webhook.Model
{
    /// <summary>
    /// AudioMessageContent
    /// </summary>
    [DataContract(Name = "AudioMessageContent")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    public partial class AudioMessageContent : MessageContent, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioMessageContent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AudioMessageContent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioMessageContent" /> class.
        /// </summary>
        /// <param name="contentProvider">contentProvider (required).</param>
        /// <param name="duration">Length of audio file (milliseconds).</param>
        /// <param name="type">Type (required) (default to &quot;AudioMessageContent&quot;).</param>
        /// <param name="id">Message ID (required).</param>
        public AudioMessageContent(ContentProvider contentProvider = default(ContentProvider), long duration = default(long), string type = @"AudioMessageContent", string id = default(string)) : base(type, id)
        {
            // to ensure "contentProvider" is required (not null)
            if (contentProvider == null)
            {
                throw new ArgumentNullException("contentProvider is a required property for AudioMessageContent and cannot be null");
            }
            this.ContentProvider = contentProvider;
            this.Duration = duration;
        }

        /// <summary>
        /// Gets or Sets ContentProvider
        /// </summary>
        [DataMember(Name = "contentProvider", IsRequired = true, EmitDefaultValue = true)]
        public ContentProvider ContentProvider { get; set; }

        /// <summary>
        /// Length of audio file (milliseconds)
        /// </summary>
        /// <value>Length of audio file (milliseconds)</value>
        [DataMember(Name = "duration", EmitDefaultValue = false)]
        public long Duration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AudioMessageContent {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  ContentProvider: ").Append(ContentProvider).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
