/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Linebotsdkx.Webhook.Client.OpenAPIDateConverter;

namespace Linebotsdkx.Webhook.Model
{
    /// <summary>
    /// A delivery object containing a hashed phone number string or a string specified by &#x60;X-Line-Delivery-Tag&#x60; header
    /// </summary>
    [DataContract(Name = "PnpDelivery")]
    public partial class PnpDelivery : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PnpDelivery" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PnpDelivery() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PnpDelivery" /> class.
        /// </summary>
        /// <param name="data">A hashed phone number string or a string specified by &#x60;X-Line-Delivery-Tag&#x60; header (required).</param>
        public PnpDelivery(string data = default(string))
        {
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for PnpDelivery and cannot be null");
            }
            this.Data = data;
        }

        /// <summary>
        /// A hashed phone number string or a string specified by &#x60;X-Line-Delivery-Tag&#x60; header
        /// </summary>
        /// <value>A hashed phone number string or a string specified by &#x60;X-Line-Delivery-Tag&#x60; header</value>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public string Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PnpDelivery {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
