/*
 * Channel Access Token API
 *
 * This document describes Channel Access Token API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.ChannelAccessToken.Model;
using Linebotsdkx.ChannelAccessToken.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.ChannelAccessToken.Test.Model
{
    /// <summary>
    ///  Class for testing IssueShortLivedChannelAccessTokenResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IssueShortLivedChannelAccessTokenResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IssueShortLivedChannelAccessTokenResponse
        //private IssueShortLivedChannelAccessTokenResponse instance;

        public IssueShortLivedChannelAccessTokenResponseTests()
        {
            // TODO uncomment below to create an instance of IssueShortLivedChannelAccessTokenResponse
            //instance = new IssueShortLivedChannelAccessTokenResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IssueShortLivedChannelAccessTokenResponse
        /// </summary>
        [Fact]
        public void IssueShortLivedChannelAccessTokenResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IssueShortLivedChannelAccessTokenResponse
            //Assert.IsType<IssueShortLivedChannelAccessTokenResponse>(instance);
        }

        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }

        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
    }
}
