/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Linebotsdkx.MessagingApi.Client.OpenAPIDateConverter;

namespace Linebotsdkx.MessagingApi.Model
{
    /// <summary>
    /// MarkMessagesAsReadRequest
    /// </summary>
    [DataContract(Name = "MarkMessagesAsReadRequest")]
    public partial class MarkMessagesAsReadRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarkMessagesAsReadRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MarkMessagesAsReadRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MarkMessagesAsReadRequest" /> class.
        /// </summary>
        /// <param name="chat">chat (required).</param>
        public MarkMessagesAsReadRequest(ChatReference chat = default(ChatReference))
        {
            // to ensure "chat" is required (not null)
            if (chat == null)
            {
                throw new ArgumentNullException("chat is a required property for MarkMessagesAsReadRequest and cannot be null");
            }
            this.Chat = chat;
        }

        /// <summary>
        /// Gets or Sets Chat
        /// </summary>
        [DataMember(Name = "chat", IsRequired = true, EmitDefaultValue = true)]
        public ChatReference Chat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MarkMessagesAsReadRequest {\n");
            sb.Append("  Chat: ").Append(Chat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
