/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Linebotsdkx.MessagingApi.Client.OpenAPIDateConverter;

namespace Linebotsdkx.MessagingApi.Model
{
    /// <summary>
    /// ReplyMessageResponse
    /// </summary>
    [DataContract(Name = "ReplyMessageResponse")]
    public partial class ReplyMessageResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplyMessageResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReplyMessageResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplyMessageResponse" /> class.
        /// </summary>
        /// <param name="sentMessages">Array of sent messages. (required).</param>
        public ReplyMessageResponse(List<SentMessage> sentMessages = default(List<SentMessage>))
        {
            // to ensure "sentMessages" is required (not null)
            if (sentMessages == null)
            {
                throw new ArgumentNullException("sentMessages is a required property for ReplyMessageResponse and cannot be null");
            }
            this.SentMessages = sentMessages;
        }

        /// <summary>
        /// Array of sent messages.
        /// </summary>
        /// <value>Array of sent messages.</value>
        [DataMember(Name = "sentMessages", IsRequired = true, EmitDefaultValue = true)]
        public List<SentMessage> SentMessages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReplyMessageResponse {\n");
            sb.Append("  SentMessages: ").Append(SentMessages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
