/*
 * Mission Stickers API
 *
 * This document describes LINE Mission Stickers API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Linebotsdkx.Shop.Client;
using Linebotsdkx.Shop.Model;

namespace Linebotsdkx.Shop.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IShopApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Sends a mission sticker.
        /// </remarks>
        /// <exception cref="Linebotsdkx.Shop.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="missionStickerRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void MissionStickerV3(MissionStickerRequest missionStickerRequest, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Sends a mission sticker.
        /// </remarks>
        /// <exception cref="Linebotsdkx.Shop.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="missionStickerRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> MissionStickerV3WithHttpInfo(MissionStickerRequest missionStickerRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IShopApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Sends a mission sticker.
        /// </remarks>
        /// <exception cref="Linebotsdkx.Shop.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="missionStickerRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task MissionStickerV3Async(MissionStickerRequest missionStickerRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Sends a mission sticker.
        /// </remarks>
        /// <exception cref="Linebotsdkx.Shop.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="missionStickerRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> MissionStickerV3WithHttpInfoAsync(MissionStickerRequest missionStickerRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IShopApi : IShopApiSync, IShopApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ShopApi : IShopApi
    {
        private Linebotsdkx.Shop.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ShopApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ShopApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShopApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ShopApi(string basePath)
        {
            this.Configuration = Linebotsdkx.Shop.Client.Configuration.MergeConfigurations(
                Linebotsdkx.Shop.Client.GlobalConfiguration.Instance,
                new Linebotsdkx.Shop.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Linebotsdkx.Shop.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Linebotsdkx.Shop.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Linebotsdkx.Shop.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShopApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ShopApi(Linebotsdkx.Shop.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Linebotsdkx.Shop.Client.Configuration.MergeConfigurations(
                Linebotsdkx.Shop.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Linebotsdkx.Shop.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Linebotsdkx.Shop.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Linebotsdkx.Shop.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShopApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ShopApi(Linebotsdkx.Shop.Client.ISynchronousClient client, Linebotsdkx.Shop.Client.IAsynchronousClient asyncClient, Linebotsdkx.Shop.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Linebotsdkx.Shop.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Linebotsdkx.Shop.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Linebotsdkx.Shop.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Linebotsdkx.Shop.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Linebotsdkx.Shop.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Sends a mission sticker.
        /// </summary>
        /// <exception cref="Linebotsdkx.Shop.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="missionStickerRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void MissionStickerV3(MissionStickerRequest missionStickerRequest, int operationIndex = 0)
        {
            MissionStickerV3WithHttpInfo(missionStickerRequest);
        }

        /// <summary>
        ///  Sends a mission sticker.
        /// </summary>
        /// <exception cref="Linebotsdkx.Shop.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="missionStickerRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Linebotsdkx.Shop.Client.ApiResponse<Object> MissionStickerV3WithHttpInfo(MissionStickerRequest missionStickerRequest, int operationIndex = 0)
        {
            // verify the required parameter 'missionStickerRequest' is set
            if (missionStickerRequest == null)
            {
                throw new Linebotsdkx.Shop.Client.ApiException(400, "Missing required parameter 'missionStickerRequest' when calling ShopApi->MissionStickerV3");
            }

            Linebotsdkx.Shop.Client.RequestOptions localVarRequestOptions = new Linebotsdkx.Shop.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Linebotsdkx.Shop.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Linebotsdkx.Shop.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = missionStickerRequest;

            localVarRequestOptions.Operation = "ShopApi.MissionStickerV3";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/shop/v3/mission", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MissionStickerV3", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Sends a mission sticker.
        /// </summary>
        /// <exception cref="Linebotsdkx.Shop.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="missionStickerRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task MissionStickerV3Async(MissionStickerRequest missionStickerRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await MissionStickerV3WithHttpInfoAsync(missionStickerRequest, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  Sends a mission sticker.
        /// </summary>
        /// <exception cref="Linebotsdkx.Shop.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="missionStickerRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Linebotsdkx.Shop.Client.ApiResponse<Object>> MissionStickerV3WithHttpInfoAsync(MissionStickerRequest missionStickerRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'missionStickerRequest' is set
            if (missionStickerRequest == null)
            {
                throw new Linebotsdkx.Shop.Client.ApiException(400, "Missing required parameter 'missionStickerRequest' when calling ShopApi->MissionStickerV3");
            }


            Linebotsdkx.Shop.Client.RequestOptions localVarRequestOptions = new Linebotsdkx.Shop.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Linebotsdkx.Shop.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Linebotsdkx.Shop.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = missionStickerRequest;

            localVarRequestOptions.Operation = "ShopApi.MissionStickerV3";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/shop/v3/mission", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MissionStickerV3", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
