/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Linebotsdkx.Module.Model;
using Linebotsdkx.Module.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Linebotsdkx.Module.Test.Model
{
    /// <summary>
    ///  Class for testing ModuleBot
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModuleBotTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModuleBot
        //private ModuleBot instance;

        public ModuleBotTests()
        {
            // TODO uncomment below to create an instance of ModuleBot
            //instance = new ModuleBot();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModuleBot
        /// </summary>
        [Fact]
        public void ModuleBotInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModuleBot
            //Assert.IsType<ModuleBot>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'BasicId'
        /// </summary>
        [Fact]
        public void BasicIdTest()
        {
            // TODO unit test for the property 'BasicId'
        }

        /// <summary>
        /// Test the property 'PremiumId'
        /// </summary>
        [Fact]
        public void PremiumIdTest()
        {
            // TODO unit test for the property 'PremiumId'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'PictureUrl'
        /// </summary>
        [Fact]
        public void PictureUrlTest()
        {
            // TODO unit test for the property 'PictureUrl'
        }
    }
}
